import Head from "next/head";
import Link from "next/link";
import Header from "~/components/Header";
import Login from "~/components/Login";
import DataKonsumen from "./datakonsumen";
import ClaimGaransi from "./claimgaransi";
import Penawaran from "./penawaran";
import ServiceMasuk from "./servicemasuk";
import ServiceKeluar from "./servicekeluar";
import Beranda from "./Beranda";
import { api } from "~/utils/api";

export default function Home() {

  return (
    <>
      <Head>
        <title>Canon Printer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login />
      </> 
    
  );
}
